/**
 * App Kit opinionated template — v0 (FLORA_APP_KIT_ARCHITECTURE.md §8 phase 3).
 *
 * The single fixed stack: a minimal Express (Node.js) app, matching every other
 * service in this codebase. Rendered as plain string interpolation — no
 * templating-engine dependency, no multi-framework support.
 *
 * `render(build, generatedRouteBody)` returns the full file set as
 * `[{ path, content }, ...]`, ready for `appKitScaffoldService.pushFiles`.
 */

function slugify(appName) {
  return String(appName)
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 90) || 'app-kit-app';
}

const DEFAULT_ROUTE_BODY =
  "    res.json({ message: 'Flora App Kit scaffold — no generated code for this route yet.' });";

function renderPackageJson(slug, buildId) {
  return `${JSON.stringify(
    {
      name: slug,
      version: '0.1.0',
      private: true,
      description: `Generated by Flora App Kit (build ${buildId})`,
      main: 'server.js',
      scripts: {
        start: 'node server.js',
        test: 'jest'
      },
      dependencies: {
        express: '^4.18.2'
      },
      devDependencies: {
        jest: '^29.7.0'
      },
      engines: {
        node: '>=18.0.0'
      }
    },
    null,
    2
  )}\n`;
}

function renderServer(appName) {
  return `require('dotenv').config();
const app = require('./src/index');

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log('${appName.replace(/'/g, "\\'")} listening on port ' + PORT);
});
`;
}

function renderIndex(buildId, routeBody) {
  return `const express = require('express');
const { callAppKit } = require('./appKitClient');

const app = express();
app.use(express.json());

app.get('/health', (req, res) => res.json({ status: 'ok' }));

// Example route — generated for App Kit build ${buildId}.
// eslint-disable-next-line no-unused-vars
app.get('/api/example', async (req, res, next) => {
  try {
${routeBody}
  } catch (err) {
    next(err);
  }
});

// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  console.error(err);
  res.status(err.statusCode || 500).json({ error: err.message || 'Internal error' });
});

module.exports = app;
`;
}

function renderAppKitClient() {
  return `/**
 * Scoped Flora data client.
 *
 * This is the ONLY sanctioned way this app may reach Flora data — there is no
 * other data-access path in this template. It POSTs { op, args } to Command
 * Center's App Kit data broker, which enforces this build's capability
 * manifest, tenant isolation, and ZDR policy, and writes every touch to the
 * audit ledger. See FLORA_APP_KIT_ARCHITECTURE.md §5.
 *
 * APP_KIT_TOKEN and COMMAND_CENTER_API_URL are injected into this app's
 * environment at deploy time — never hardcode credentials here.
 */

async function callAppKit(op, args = {}) {
  const token = process.env.APP_KIT_TOKEN;
  const baseUrl = process.env.COMMAND_CENTER_API_URL;

  if (!token) {
    throw new Error('APP_KIT_TOKEN is not set — this app has no scoped access to Flora data');
  }
  if (!baseUrl) {
    throw new Error('COMMAND_CENTER_API_URL is not set');
  }

  const response = await fetch(\`\${baseUrl}/api/command-center/appkit/data\`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: \`Bearer \${token}\`
    },
    body: JSON.stringify({ op, args })
  });

  const body = await response.json().catch(() => ({}));

  if (!response.ok || body.success === false) {
    throw new Error(body.error || \`App Kit call failed: \${op} (HTTP \${response.status})\`);
  }

  return body.data;
}

module.exports = { callAppKit };
`;
}

function renderDataIntegrityTest() {
  return `const { callAppKit } = require('../src/appKitClient');

/**
 * Data-integrity test scaffolding for the scoped App Kit client (the "easy to
 * use and quietly wrong" guard called out in Block's App Kit article). This
 * exercises the client's wiring — request shape, auth header, error surfacing
 * — against a mocked broker call. It does not, and cannot, verify the
 * manifest itself; that is enforced server-side by Command Center and
 * statically checked by devops before deploy.
 */
describe('appKitClient', () => {
  const ORIGINAL_ENV = process.env;

  beforeEach(() => {
    process.env = {
      ...ORIGINAL_ENV,
      APP_KIT_TOKEN: 'test-token',
      COMMAND_CENTER_API_URL: 'https://command-center.example.com'
    };
    global.fetch = jest.fn();
  });

  afterEach(() => {
    process.env = ORIGINAL_ENV;
    jest.resetAllMocks();
  });

  it('POSTs { op, args } with a bearer token to the data broker endpoint', async () => {
    global.fetch.mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({ success: true, data: { id: 'cmp_1' } })
    });

    const data = await callAppKit('getCompany', { companyId: 'cmp_1' });

    expect(global.fetch).toHaveBeenCalledWith(
      'https://command-center.example.com/api/command-center/appkit/data',
      expect.objectContaining({
        method: 'POST',
        headers: expect.objectContaining({ Authorization: 'Bearer test-token' }),
        body: JSON.stringify({ op: 'getCompany', args: { companyId: 'cmp_1' } })
      })
    );
    expect(data).toEqual({ id: 'cmp_1' });
  });

  it('surfaces the broker error message when a call is denied', async () => {
    global.fetch.mockResolvedValue({
      ok: false,
      status: 403,
      json: async () => ({
        success: false,
        error: "Manifest denies operation: Resource 'company' not declared"
      })
    });

    await expect(callAppKit('getCompany', { companyId: 'cmp_1' })).rejects.toThrow(
      /Manifest denies operation/
    );
  });

  it('refuses to call out with no APP_KIT_TOKEN configured', async () => {
    delete process.env.APP_KIT_TOKEN;
    await expect(callAppKit('getCompany', {})).rejects.toThrow(/APP_KIT_TOKEN/);
    expect(global.fetch).not.toHaveBeenCalled();
  });
});
`;
}

function renderCiWorkflow() {
  return `name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
`;
}

function renderReadme(appName, buildId) {
  return `# ${appName}

This app was generated by Flora App Kit (build \`${buildId}\`). It reads and writes
Flora data only through the scoped \`src/appKitClient.js\` client, which is
brokered by Command Center according to this build's declared capability
manifest — there is no other data-access path in this app.
`;
}

/**
 * Render the full opinionated-stack file set for a build.
 * @param {import('../../models/AppKitBuild')} build
 * @param {string} [generatedRouteBody] - best-effort code from
 *   appKitGenerateService, spliced into the example route's try block. Falls
 *   back to a placeholder response when generation produced nothing usable.
 * @returns {Array<{ path: string, content: string }>}
 */
function render(build, generatedRouteBody) {
  const appName = build.appName;
  const buildId = build.buildId;
  const slug = slugify(appName);
  const routeBody = (generatedRouteBody && generatedRouteBody.trim()) || DEFAULT_ROUTE_BODY;

  return [
    { path: 'package.json', content: renderPackageJson(slug, buildId) },
    { path: 'server.js', content: renderServer(appName) },
    { path: 'src/index.js', content: renderIndex(buildId, routeBody) },
    { path: 'src/appKitClient.js', content: renderAppKitClient() },
    { path: 'tests/data-integrity.test.js', content: renderDataIntegrityTest() },
    { path: '.github/workflows/ci.yml', content: renderCiWorkflow() },
    { path: 'README.md', content: renderReadme(appName, buildId) }
  ];
}

module.exports = { render, slugify };
